apiVersion: v1
  kind: Service
  metadata:
    name: node-loadbalancer-service
    labels:
    app: node
  spec:
    type: LoadBalancer
    selector:
    app: node
      ports:
      - port: 30
        targetPort: 3000