
name: Build and deploy an nodejs app to AKS

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

env:
  REGISTRY_NAME: registryzcamprivage2022
  CLUSTER_NAME: aks-cluster-ZCampRivage2022
  CLUSTER_RESOURCE_GROUP: rg-zcamprivage2022
  APP_NAME: node

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      # Connect to Azure Container Registry (ACR)
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Container build and push to a Azure Container Registry (ACR)
      - run: |
          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        working-directory: ./<path-to-Dockerfile-directory>